In [14]:
import pandas as pd
from glob import glob

csv_list = glob("data/*.csv")
df_list = list()

for directory in csv_list:
    df = pd.read_csv(directory)
    df["MMYYYY"] = df["FL_DATE"].apply(lambda x: "".join(x.split("-")[:-1]))
    sampled_data = df.groupby('MMYYYY').apply(lambda x: x.sample(n=100000)).reset_index(drop=True)
    df_list.append(sampled_data)
df = pd.concat(df_list)
len(df)

C:\Users\wongh\AppData\Local\Temp\ipykernel_15884\1504122073.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_data = df.groupby('MMYYYY').apply(lambda x: x.sample(n=100000)).reset_index(drop=True)
C:\Users\wongh\AppData\Local\Temp\ipykernel_15884\1504122073.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_data = df.groupby('MMYYYY').apply(lambda x: x.sample(n=100000)).reset_index(drop=True)
C:\Users\wongh\AppData\Local\Temp\ipykernel_15884\1504122073.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_data = df.groupby('MMYYYY').apply(lambda x: x.sample(n=100000)).reset_index(drop=True)
C:\Users\wongh\AppData\Local\Temp\ipykernel_15884\1504122073.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_data = df.groupby('MMYYYY').apply(lambda x: x.sample(n=100000)).reset_index(drop=True)

12000000

In [17]:
df.drop_duplicates(inplace = True)
print("Duplicate Row Percent {}%".format((12000000 - len(df))/12000000)*100)

11991358

In [23]:
df.reset_index(drop=True, inplace = True)

In [26]:
from ydata_profiling import ProfileReport
from IPython.display import IFrame
import os

html_report_path = "html/T_ONTIME_REPORTING_TOTAL.html"

os.makedirs("html", exist_ok = True)
# generate a dataframe profile
ProfileReport(df).to_file(html_report_path)
IFrame(src=html_report_path, width=700, height=600)

Summarize dataset: 100%|██████████████████████████████████████████████████| 362/362 [28:09<00:00,  4.67s/it, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:13<00:00, 13.32s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:10<00:00, 10.81s/it]
Export report to file: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.92it/s]

In [36]:
df.columns

Index(['FL_DATE', 'OP_UNIQUE_CARRIER', 'OP_CARRIER', 'TAIL_NUM',
       'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID',
       'ORIGIN', 'ORIGIN_CITY_NAME', 'DEST_AIRPORT_ID', 'DEST_AIRPORT_SEQ_ID',
       'DEST_CITY_MARKET_ID', 'DEST', 'DEST_CITY_NAME', 'DEP_TIME',
       'DEP_DELAY', 'TAXI_OUT', 'TAXI_IN', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'CARRIER_DELAY', 'WEATHER_DELAY',
       'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY', 'MMYYYY'],
      dtype='object')

In [62]:
for it, row in df.loc[:, ['OP_CARRIER', 'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID']].drop_duplicates().reset_index(drop = True).iterrows():
    print(row['ORIGIN'], row['ORIGIN_AIRPORT_SEQ_ID'], it)

MIA 1330303 0
JFK 1247802 1
MCO 1320402 2
LAX 1289203 3
ATL 1039705 4
SJC 1483103 5
SFO 1477101 6
HOU 1219102 7
ORD 1393003 8
BOS 1072102 9
IAH 1226603 10
ABQ 1014003 11
PHX 1410702 12
TPA 1530402 13
TUL 1537002 14
TUS 1537602 15
OGG 1383002 16
BWI 1082103 17
RNO 1457002 18
DAL 1125903 19
SAN 1467903 20
IAD 1226402 21
DAY 1126702 22
CLT 1105703 23
SJU 1484304 24
DTW 1143302 25
SCE 1471102 26
EWR 1161802 27
LGA 1295302 28
PDX 1405702 29
SLC 1486903 30
LAS 1288903 31
AMA 1027903 32
MDW 1323202 33
DCA 1127802 34
CMH 1106603 35
HNL 1217302 36
SDF 1473003 37
BDL 1052904 38
PSE 1425403 39
MCI 1319801 40
DFW 1129803 41
SMF 1489302 42
COD 1109702 43
SJT 1484202 44
SEA 1474703 45
BNA 1069302 46
SPS 1496002 47
ANC 1029904 48
SAT 1468303 49
OKC 1385103 50
DEN 1129202 51
MSP 1348702 52
FLL 1169703 53
PHL 1410002 54
OMA 1387102 55
CLE 1104203 56
LIH 1298202 57
OAK 1379603 58
SGF 1478302 59
HLN 1215602 60
MSY 1349503 61
SHV 1481402 62
RIC 1452401 63
BUF 1079204 64
LFT 1295103 65
DBQ 1127402 66
CHS 1099402 67
IND 1233904 68
AUS 1042302 69
PNS 1419304 70
VLD 1560702 71
SBN 1469606 72
MSN 1348502 73
IDA 1228002 74
GEG 1188402 75
BUR 1080003 76
PUB 1428803 77
RDU 1449202 78
SNA 1490803 79
PIA 1410803 80
JAC 1244102 81
TRI 1532302 82
OTZ 1397002 83
MKE 1334205 84
FSM 1177801 85
PIT 1412202 86
SAF 1467402 87
PVD 1430702 88
SAV 1468502 89
BTV 1078502 90
XNA 1591902 91
TVC 1538003 92
PIH 1411302 93
RSW 1463502 94
MAF 1315802 95
ELP 1154003 96
BIL 1062002 97
TLH 1524903 98
LIT 1299204 99
FAT 1163805 100
BOI 1071302 101
MHT 1329604 102
SIT 1482803 103
GGG 1190502 104
BHM 1059904 105
ONT 1389101 106
HPN 1219702 107
COS 1110902 108
STL 1501603 109
GRB 1197702 110
MDT 1323002 111
JNU 1252303 112
CMI 1106702 113
KOA 1275803 114
TYS 1541202 115
MEM 1324402 116
WYS 1589702 117
ORF 1393102 118
SUN 1504102 119
GJT 1192102 120
BZN 1084903 121
LGB 1295402 122
MOT 1343302 123
ISP 1239102 124
SPI 1495203 125
BJI 1063104 126
LRD 1306104 127
RKS 1454302 128
STT 1502403 129
DSM 1142303 130
YUM 1621801 131
EVV 1161203 132
GPT 1197302 133
CID 1100303 134
TYR 1541103 135
GRR 1198603 136
DRO 1141303 137
ICT 1227802 138
AEX 1018502 139
GSO 1199502 140
SWF 1507002 141
MLI 1336703 142
MGM 1327702 143
ACT 1015502 144
BFL 1056103 145
FSD 1177502 146
ROC 1457604 147
PBI 1402702 148
GRK 1198202 149
TOL 1529502 150
MOB 1342202 151
SBP 1469802 152
FLG 1169502 153
BTR 1078102 154
FAR 1163703 155
RAP 1445702 156
WRG 1584102 157
BMI 1068502 158
TXK 1540103 159
VPS 1562401 160
CAK 1087402 161
GCC 1186502 162
SBA 1468902 163
LEX 1294503 164
CRP 1114004 165
CVG 1119302 166
PWM 1432103 167
MKG 1334402 168
HRL 1220603 169
AVL 1043102 170
CWA 1120302 171
ALB 1025702 172
CRW 1114604 173
GSP 1199603 174
DLH 1133703 175
TTN 1535602 176
ECP 1148102 177
MBS 1318403 178
MFR 1326403 179
MFE 1325602 180
FCA 1164802 181
CEC 1093002 182
FAY 1164102 183
RDM 1448902 184
JAN 1244805 185
RST 1463303 186
GTF 1200302 187
JAX 1245102 188
SMX 1490503 189
ERI 1157704 190
ROA 1457402 191
EYW 1162402 192
BGR 1058102 193
GST 1199702 194
FNT 1172102 195
STC 1500802 196
PSP 1426202 197
ACV 1015703 198
SYR 1509602 199
BQK 1073103 200
LSE 1307602 201
HSV 1221702 202
FWA 1182304 203
GUC 1201202 204
SRQ 1498603 205
MYR 1357702 206
GNV 1195302 207
ILG 1232002 208
HYA 1225002 209
CPR 1112203 210
IMT 1233502 211
BRW 1075402 212
LAN 1288403 213
OME 1387302 214
ELM 1153703 215
ITO 1240203 216
CHO 1099002 217
ILM 1232303 218
BTM 1077902 219
MRY 1347603 220
PSG 1425603 221
EUG 1160302 222
CAE 1086803 223
DHN 1130802 224
AZO 1046902 225
MSO 1348602 226
TWF 1538902 227
BET 1055102 228
ABY 1014602 229
BIS 1062702 230
LAW 1289102 231
FAI 1163002 232
PSC 1425202 233
CHA 1098002 234
CLL 1104902 235
GRI 1198002 236
AVP 1043403 237
EKO 1152502 238
RDD 1448702 239
BQN 1073203 240
LNK 1302902 241
MHK 1329002 242
EAU 1147103 243
BRD 1073905 244
CDV 1092603 245
BRO 1074702 246
VEL 1558202 247
CIC 1100202 248
MLU 1337702 249
JMS 1251902 250
MTJ 1350202 251
KTN 1281902 252
LBB 1289605 253
PHF 1409803 254
DAB 1125203 255
ADK 1016502 256
AGS 1020803 257
GUM 1201602 258
ISN 1238902 259
ABI 1013603 260
CLD 1104103 261
BPT 1072804 262
GFK 1189802 263
ASE 1037203 264
CIU 1101303 265
APN 1033302 266
LCH 1291503 267
DIK 1131502 268
AKN 1024502 269
MVY 1354102 270
RHI 1452002 271
PLN 1415002 272
MQT 1345902 273
COU 1111102 274
GTR 1200702 275
HIB 1212903 276
CNY 1109202 277
ALO 1026802 278
ABE 1013503 279
ABR 1014103 280
EGE 1150303 281
DLG 1133602 282
PAH 1400602 283
ACK 1015403 284
YAK 1599102 285
HOB 1217703 286
CSG 1115003 287
EWN 1161706 288
GCK 1186703 289
FOE 1172602 290
STX 1502704 291
INL 1234302 292
MLB 1336003 293
ORH 1393303 294
SGU 1479402 295
ACY 1015804 296
LAR 1288802 297
BLI 1066602 298
ATW 1040802 299
CMX 1107602 300
SUX 1504803 301
DVL 1144703 302
SCC 1470903 303
JLN 1251102 304
OAJ 1379502 305
CDC 1091802 306
OTH 1396403 307
ROW 1458801 308
LWS 1312702 309
HDN 1209402 310
ADQ 1017001 311
PPG 1422204 312
BKG 1064301 313
UST 1549703 314
HYS 1225502 315
PIB 1410902 316
MEI 1324102 317
ESC 1158702 318
MMH 1338801 319
LBE 1289803 320
IAG 1226503 321
PBG 1402501 322
BGM 1057703 323
ITH 1239702 324
FLL 1169704 325
DFW 1129804 326
SFO 1477102 327
CRP 1114005 328
ICT 1227803 329
OAK 1379604 330
LSE 1307603 331
EVV 1161204 332
OME 1387303 333
BRW 1075403 334
EKO 1152503 335
INL 1234303 336
HLN 1215603 337
LFT 1295104 338
TLH 1524904 339
PSP 1426203 340
OTZ 1397003 341
GUC 1201203 342
JFK 1247803 343
DCA 1127803 344
PSP 1426204 345
BTR 1078103 346
DRO 1141304 347
ATW 1040803 348
VPS 1562402 349
ADK 1016503 350
ORD 1393004 351
TYS 1541203 352
FNT 1172103 353
JNU 1252304 354
AVL 1043103 355
DSM 1142304 356
ROA 1457403 357
SGU 1479403 358
BWI 1082104 359
LAX 1289204 360
LBE 1289804 361
ADK 1016504 362
SJC 1483104 363
LGB 1295403 364
CRP 1114006 365
GRB 1197703 366
PGD 1408202 367
SPN 1495503 368
CHO 1099003 369
STS 1502303 370
IFP 1059003 371
LAX 1289205 372
MAF 1315803 373
IFP 1059004 374
ABR 1014104 375
LGB 1295404 376
LAX 1289206 377
HNL 1217303 378
PVD 1430703 379
OAK 1379605 380
CMH 1106604 381
PHL 1410003 382
STL 1501604 383
GTF 1200303 384
TRI 1532303 385
BRO 1074703 386
SCE 1471103 387
ROW 1458802 388
OAK 1379606 389
ADQ 1017002 390
ACV 1015704 391
COU 1111103 392
SCC 1470904 393
SFO 1477103 394
LGA 1295303 395
LAX 1289207 396
FLL 1169705 397
SAT 1468304 398
PHL 1410004 399
ATL 1039706 400
ORD 1393005 401
DCA 1127804 402
FNT 1172104 403
DFW 1129805 404
CLE 1104204 405
BWI 1082105 406
HNL 1217304 407
ELP 1154004 408
PSG 1425604 409
DSM 1142305 410
MSY 1349504 411
ABQ 1014004 412
OAK 1379607 413
BUF 1079205 414
STL 1501605 415
CHO 1099004 416
PVD 1430704 417
CRW 1114605 418
GTR 1200703 419
SIT 1482804 420
ERI 1157705 421
SJC 1483105 422
JFK 1247804 423
BDL 1052905 424
SBN 1469607 425
ANC 1029905 426
HLN 1215604 427
ABE 1013504 428
STS 1502304 429
MKE 1334206 430
CMH 1106605 431
TLH 1524905 432
JAN 1244806 433
GRB 1197704 434
LBB 1289606 435
EKO 1152504 436
MRY 1347604 437
TYS 1541204 438
SJU 1484305 439
ICT 1227804 440
LGB 1295405 441
BTR 1078104 442
ATW 1040804 443
FAT 1163806 444
XNA 1591903 445
LFT 1295105 446
PNS 1419305 447
HRL 1220604 448
VPS 1562403 449
BZN 1084904 450
MLI 1336704 451
JNU 1252305 452
ASE 1037204 453
CRP 1114007 454
ROC 1457605 455
SGU 1479404 456
AVL 1043104 457
LIT 1299205 458
LBE 1289805 459
PWM 1432104 460
ADQ 1017003 461
MAF 1315804 462
AVP 1043404 463
ILM 1232304 464
GTF 1200304 465
DVL 1144704 466
SCE 1471104 467
BRD 1073906 468
COU 1111104 469
BGM 1057704 470
LSE 1307604 471
CPR 1112204 472
BRO 1074704 473
EVV 1161205 474
TVC 1538004 475
LRD 1306105 476
HOB 1217704 477
DRO 1141305 478
BRW 1075404 479
OTZ 1397004 480
TRI 1532304 481
CKB 1102704 482
IAG 1226504 483
ADK 1016505 484
OME 1387304 485
ABR 1014105 486
ROW 1458803 487
ACV 1015705 488
ORH 1393304 489
ROA 1457404 490
IFP 1059005 491
INL 1234304 492
EGE 1150304 493
PPG 1422205 494
JFK 1247805 495
CMH 1106606 496
ATL 1039707 497
BWI 1082106 498
LAX 1289208 499
ANC 1029906 500
PWM 1432105 501
SFO 1477104 502
PVD 1430705 503
DCA 1127805 504
SAT 1468305 505
LGA 1295304 506
DFW 1129806 507
FLL 1169706 508
SJC 1483106 509
ORD 1393006 510
OAK 1379608 511
PHL 1410005 512
HNL 1217305 513
STL 1501606 514
MSY 1349505 515
MKE 1334207 516
TVC 1538005 517
BDL 1052906 518
ILM 1232305 519
LIT 1299206 520
SJU 1484306 521
BTR 1078105 522
CLE 1104205 523
BUF 1079206 524
ABQ 1014005 525
ORH 1393305 526
MLI 1336705 527
KOA 1275804 528
AVP 1043405 529
ICT 1227805 530
LGB 1295406 531
DSM 1142306 532
SCE 1471105 533
XNA 1591904 534
ROC 1457606 535
HLN 1215605 536
ROW 1458804 537
MRY 1347605 538
FAT 1163807 539
AVL 1043105 540
TYS 1541205 541
ASE 1037205 542
BZN 1084905 543
SBN 1469608 544
ERI 1157706 545
LBB 1289607 546
ATW 1040805 547
LRD 1306106 548
JAN 1244807 549
COU 1111105 550
ELP 1154005 551
VPS 1562404 552
CRP 1114008 553
MAF 1315805 554
ABE 1013505 555
JNU 1252306 556
DRO 1141306 557
EGE 1150305 558
CHO 1099005 559
ADQ 1017004 560
EVV 1161206 561
CRW 1114606 562
GTF 1200305 563
LSE 1307605 564
STS 1502305 565
HRL 1220605 566
TLH 1524906 567
FNT 1172105 568
PNS 1419306 569
SIT 1482805 570
OME 1387305 571
ADK 1016506 572
BIL 1062003 573
LFT 1295106 574
GRB 1197705 575
HOB 1217705 576
OTZ 1397005 577
GTR 1200704 578
DVL 1144705 579
SGU 1479405 580
ACV 1015706 581
ROA 1457405 582
TRI 1532305 583
CKB 1102705 584
ABR 1014106 585
IFP 1059006 586
INL 1234305 587
BGM 1057705 588
CGI 1096702 589
PSG 1425605 590
EKO 1152505 591
UIN 1545405 592
LBE 1289806 593
PSE 1425404 594
CPR 1112205 595
PUB 1428805 596
IAG 1226505 597
GUC 1201205 598
BRD 1073907 599
BRO 1074705 600
BRW 1075405 601
ELM 1153705 602
PPG 1422206 603
SWO 1507402 604
AZA 1046602 605
SFB 1476106 606
CSG 1115005 607
USA 1254403 608
TYR 1541105 609
PIE 1411206 610
EWN 1161708 611
LYH 1313902 612
BLV 1067602 613
PVU 1431402 614
HVN 1224402 615
SCK 1471602 616
RFD 1451202 617
YNG 1613305 618
LCK 1291703 619
HTS 1222305 620
OGS 1383205 621
OGD 1382902 622
OWB 1398305 623
PSM 1425902 624
SMX 1490505 625
BFF 1055803 626
LBF 1289902 627
LBL 1290205 628
HGR 1211902 629
FLO 1169902 630
TUS 1537603 631
JLN 1251103 632
PGV 1409205 633
LWB 1312102 634
SLN 1487706 635
SHD 1480202 636
ACK 1015405 637
VEL 1558203 638
HHH 1212402 639
PRC 1423705 640
ORD 1393007 641
LGB 1295407 642
DAL 1125904 643
TUS 1537604 644
ISP 1239103 645
DSM 1142307 646
STC 1500803 647
RKS 1454303 648
BRO 1074706 649
CYS 1123302 650
YUM 1621802 651
MQT 1345903 652
MKG 1334403 653
DRT 1141501 654
EAR 1146802 655
HVN 1224403 656
TYR 1541106 657
ART 1036105 658
CNY 1109203 659
USA 1254404 660
CRW 1114607 661
PIR 1412002 662
PAE 1400402 663
EYW 1162403 664
CNY 1109204 665
CLL 1104903 666
ATY 1040903 667
BFM 1056202 668
DLH 1133704 669
BZN 1084906 670
SFB 1476107 671
SWF 1507003 672
BMI 1068503 673
SUX 1504804 674
ELM 1153706 675
PPG 1422207 676
PRC 1423706 677
SCK 1471603 678
SDF 1473004 679
DLH 1133705 680
XWA 1686901 681
OGD 1382903 682
BZN 1084907 683
DRO 1141307 684
ABE 1013506 685
MHK 1329003 686
RIW 1453402 687
SHR 1481202 688
DDC 1128302 689
DEC 1128802 690
CDB 1091706 691
IPT 1236504 692
VCT 1556902 693
ALS 1027205 694
JST 1255905 695
ALW 1027506 696
PUW 1430303 697
EAT 1147005 698
YKM 1610102 699
FOD 1172502 700
MCW 1321105 701
TBN 1513802 702
BIH 1061705 703
ORD 1393008 704
LAS 1288904 705
DSM 1142308 706
OAK 1379609 707
PGD 1408203 708
TYS 1541206 709
HOU 1219103 710
BDL 1052907 711
MHT 1329605 712
PVD 1430706 713
OME 1387306 714
BLV 1067603 715
FAI 1163003 716
PSC 1425203 717
MFR 1326404 718
ROC 1457607 719
XNA 1591905 720
ROW 1458805 721
RDM 1448903 722
ROA 1457406 723
CMX 1107603 724
CRW 1114608 725
AVL 1043106 726
PAE 1400403 727
FSM 1177802 728
SHV 1481403 729
SCK 1471604 730
COU 1111106 731
MSO 1348603 732
MLU 1337703 733
MLI 1336706 734
ALO 1026803 735
CMI 1106703 736
SUX 1504805 737
XWA 1686902 738
MLB 1336004 739
RIW 1453403 740
GCC 1186503 741
VCT 1556903 742
ITH 1239703 743
HYA 1225003 744
TOL 1529503 745
CNY 1109205 746
LYH 1313903 747
DIK 1131503 748
PPG 1422208 749
OAK 1379610 750
MFE 1325603 751
MLI 1336707 752
RDD 1448703 753
ACK 1015406 754
BPT 1072805 755
DIK 1131504 756
GUC 1201206 757
MQT 1345904 758
FSM 1177803 759

In [70]:
temp = df.groupby('OP_UNIQUE_CARRIER')['OP_CARRIER'].nunique()
temp

OP_UNIQUE_CARRIER
9E    1
AA    1
AS    1
B6    1
DL    1
EV    1
F9    1
FL    1
G4    1
HA    1
MQ    1
NK    1
OH    1
OO    1
QX    1
UA    1
US    1
VX    1
WN    1
YV    1
YX    1
Name: OP_CARRIER, dtype: int64

In [41]:
df.loc[:, ['ORIGIN']].drop_duplicates().reset_index(drop = True)

    ORIGIN
0      MIA
1      JFK
2      MCO
3      LAX
4      ATL
..     ...
382    YKM
383    FOD
384    MCW
385    TBN
386    BIH

[387 rows x 1 columns]

## Remove Duplicate Column

In [1]:
import pandas as pd
from glob import glob

csv_list = glob("data/*.csv")

for i, directory in enumerate(csv_list):
    df = pd.read_csv(directory)
    df.drop(columns=['ORIGIN_AIRPORT_ID', 'DEST_AIRPORT_ID', 'OP_CARRIER'], inplace=True)

    if i == 0:
        df.to_csv("data/Total_Data_10Y.csv", index = False)
    else:
        df.to_csv("data/Total_Data_10Y.csv", mode = "a", index = False)

In [28]:
from datetime import datetime

df.FL_DATE = df.FL_DATE.apply(lambda x: datetime.strptime(x, "%m/%d/%Y %I:%M:%S %p"))
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER,TAIL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,...,TAXI_IN,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2019-09-01,9E,9E,N131EV,11423,1142307,31423,DSM,"Des Moines, IA",13487,...,5.0,1614.0,-42.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-09-01,9E,9E,N131EV,11996,1199603,31871,GSP,"Greer, SC",12953,...,13.0,1000.0,-21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-09-01,9E,9E,N131EV,12953,1295304,31703,LGA,"New York, NY",11423,...,4.0,1250.0,-17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-09-01,9E,9E,N131EV,13487,1348702,31650,MSP,"Minneapolis, MN",13931,...,8.0,2129.0,-14.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-09-01,9E,9E,N132EV,10397,1039707,30397,ATL,"Atlanta, GA",15249,...,3.0,2316.0,-13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
filtered_df = df[(df['FL_DATE'] >= '2014-07-01') & (df['FL_DATE']  <= '2024-07-01')]
len(filtered_df)

1199821

In [30]:
print(df.loc[:, "FL_DATE"].max(), df.loc[:, "FL_DATE"].min())

2019-09-30 00:00:00 2018-12-01 00:00:00

In [31]:
sampled_df = filtered_df.sample(n=10000, random_state=42)

In [32]:
sampled_df["MY"] = sampled_df["FL_DATE"].dt.strftime('%Y-%m')
month_count = sampled_df.groupby("MY").size().reset_index(name='count')
for row in month_count.iterrows():
    print(row)

(0, MY       2018-12
count       4984
Name: 0, dtype: object)
(1, MY       2019-09
count       5016
Name: 1, dtype: object)

In [33]:
filtered_df.to_csv("data/Target_Data4.csv", index = False)

In [7]:
df[df.FL_DATE == "1/1/2013 12:00:00 AM"].head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER,TAIL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,...,TAXI_IN,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,1/1/2013 12:00:00 AM,9E,9E,NaN,10397,1039705,30397,ATL,"Atlanta, GA",11612,...,NaN,NaN,NaN,1.0,A,NaN,NaN,NaN,NaN,NaN
1,1/1/2013 12:00:00 AM,9E,9E,NaN,12264,1226402,30852,IAD,"Washington, DC",11433,...,NaN,NaN,NaN,1.0,A,NaN,NaN,NaN,NaN,NaN
2,1/1/2013 12:00:00 AM,9E,9E,NaN,12451,1245102,31136,JAX,"Jacksonville, FL",12478,...,NaN,NaN,NaN,1.0,A,NaN,NaN,NaN,NaN,NaN
3,1/1/2013 12:00:00 AM,9E,9E,N146PQ,10397,1039705,30397,ATL,"Atlanta, GA",11982,...,6.0,2124.0,-5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1/1/2013 12:00:00 AM,9E,9E,N147PQ,10397,1039705,30397,ATL,"Atlanta, GA",12278,...,4.0,2049.0,-11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
import json

meta_dict = {
    'FL_DATE': "Flight Date (yyyymmdd)",
    'OP_UNIQUE_CARRIER': "Unique Carrier Code. When the same code has been used by multiple carriers, a numeric suffix is used for earlier users, for example, PA, PA(1), PA(2). Use this field for analysis across a range of years.",
    "OP_CARRIER_FL_NUM": "Flight Number (??????)",
    "ORIGIN_AIRPORT_ID": "An identification number assigned by US DOT to identify a unique airport. Use this field for airport analysis across a range of years because an airport can change its airport code and airport codes can be reused.",
    "ORIGIN_AIRPORT_SEQ_ID": "Origin Airport, Airport Sequence ID. An identification number assigned by US DOT to identify a unique airport at a given point of time. Airport attributes, such as airport name or coordinates, may change over time.",
    "ORIGIN_CITY_MARKET_ID": "City Market ID is an identification number assigned by US DOT to identify a city market. Use this field to consolidate airports serving the same city market.",
    "ORIGIN": "Origin Airport",
    "ORIGIN_CITY_NAME": "Origin Airport, City Name",
    "DEST_AIRPORT_ID": "Use this field for airport analysis across a range of years because an airport can change its airport code and airport codes can be reused.",
    "DEST_AIRPORT_SEQ_ID": "An identification number assigned by US DOT to identify a unique airport at a given point of time. Airport attributes, such as airport name or coordinates, may change over time.",
    "DEST_CITY_MARKET_ID": "Destination Airport, City Name",
    "DEST": "Destination Airport",
    "DEST_CITY_NAME": "Destination Airport, City Name",
    "DEP_TIME": "Actual Departure Time (local time: hhmm)",
    "DEP_DELAY": "Difference in minutes between scheduled and actual departure time. Early departures show negative numbers.",
    "TAXI_OUT": "Taxi Out Time, in Minutes",
    'ARR_TIME': "Actual Arrival Time (local time: hhmm)	",
    'ARR_DELAY': "Difference in minutes between scheduled and actual arrival time. Early arrivals show negative numbers.",
    "CANCELLED": "Cancelled Flight Indicator (1=Yes)",
    "CANCELLATION_CODE": "Specifies The Reason For Cancellation",
    "DIVERTED": "Diverted Flight Indicator (1=Yes)"
}
with open("column_description.json", "w") as fp:
    json.dump(meta_dict, fp, indent = 4)

In [19]:
from ydata_profiling import ProfileReport
from IPython.display import IFrame
import os

html_report_path = "html/T_ONTIME_REPORTING.html"

os.makedirs("html", exist_ok = True)
# generate a dataframe profile
ProfileReport(df).to_file(html_report_path)
IFrame(src=html_report_path, width=700, height=600)

Summarize dataset:   0%|                                                                        | 0/26 [00:02<?, ?it/s]

KeyboardInterrupt:

## Supplementary Datasets

### Tail Num Description

In [ ]:
import pandas as pd

master = pd.read_csv("../data/Tail_Num/MASTER.csv", dtype = {
    'ENG MFR MDL': str, 'MFR MDL CODE': str, 'TYPE AIRCRAFT': str, 'TYPE ENGINE':str
})
MFR_code = pd.read_csv("../data/Tail_Num/ACFTREF.csv", dtype = {'CODE': str})
ENG_code = pd.read_csv("../data/Tail_Num/ENGINE.csv", dtype = {'CODE': str})

merge_df = pd.merge(master, MFR_code, left_on='MFR MDL CODE', right_on='CODE', how='inner', suffixes = ("_CARRIER", "_PLANE"))
merge_df = pd.merge(merge_df, ENG_code, left_on='ENG MFR MDL', right_on='CODE', how='left', suffixes = ("", "_ENGINE"))
merge_df.head()

In [ ]:
merge_df.loc[0, :]

In [ ]:
selected_columns = merge_df.loc[:, [
    "N-NUMBER", "COUNTRY", "TYPE AIRCRAFT", "TYPE ENGINE", 
    "MFR", "MODEL", "NO-ENG", "NO-SEATS", "AC-WEIGHT", 
    "MFR_ENGINE", "MODEL_ENGINE", "HORSEPOWER", "THRUST"
]]
selected_columns

In [ ]:
type_aircraft_dict = {
    "1": "Glider",
    "2": "Balloon",
    "3": "Blimp/Dirigible",
    "4": "Fixed wing single engine",
    "5": "Fixed wing multi engine",
    "6": "Rotorcraft",
    "7": "Weight-shift-control",
    "8": "Powered Parachute",
    "9": "Gyroplane",
    "H": "Hybrid Lift",
    "O": "Other",
}

type_engine_dict = {
    "0": "None",
    "1": "Reciprocating",
    "2": "Turbo-prop",
    "3": "Turbo-shaft",
    "4": "Turbo-jet",
    "5": "Turbo-fan",
    "6": "Ramjet",
    "7": "2 Cycle",
    "8": "4 Cycle",
    "9": "Unknown",
    "10": "Electric",
    "11": "Rotary",
}

ac_weight_dict = {
    "CLASS 1": "Up to 12,499",
    "CLASS 2": "12,500 - 19,999",
    "CLASS 3": "20,000 and over",
    "CLASS 4": "UAV up to 55"
}

selected_columns['TYPE AIRCRAFT'] = selected_columns['TYPE AIRCRAFT'].apply(lambda x:type_aircraft_dict[x.strip()])
selected_columns['TYPE ENGINE'] = selected_columns['TYPE ENGINE'].apply(lambda x:type_engine_dict[x.strip()])
selected_columns['AC-WEIGHT'] = selected_columns['AC-WEIGHT'].apply(lambda x:ac_weight_dict[x.strip()])
selected_columns.head()

In [ ]:
selected_columns.to_csv("N-Number-Registration-Data-2024.csv", index = False)

### Reviews

In [ ]:
import pandas as pd
from glob import glob
import os

def read_reviews_to_df(folder, file_column = "filename"):
    dfs = []
    for file_path in glob(os.path.join(folder, "*.csv")):
        df = pd.read_csv(file_path)
        df[file_column] = os.path.basename(file_path).split(".")[0]
        dfs.append(df)
    return pd.concat(dfs, ignore_index=True)

airport_review_df = read_reviews_to_df("../reviews/cleaned_airport", "AIRPORT_CODE")
airline_review_df = read_reviews_to_df("../reviews/cleaned_airline", "AIRLINE_CODE")
print(len(airport_review_df), len(airline_review_df))

In [ ]:
airport_review_df.to_csv("../supplementary/Airport-Reviews-Table.csv", index = False)
airline_review_df.to_csv("../supplementary/Airline-Reviews-Table.csv", index = False)